import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyThemeProvider from "@/components/provider/ThemeProvider";
import { Header } from "@/components/nav/Header";
import { Footer } from "@/components/footer/Footer";
import { ScrollProvider } from "@/components/provider/ScrollProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className="h-full scroll-my-20 scroll-smooth"
            suppressHydrationWarning
        >
            <body className={`flex flex-col min-h-screen antialiased`}>
                <MyThemeProvider>
                    <ScrollProvider>
                        <Header />
                        <main className="flex-1 min-h-screen pt-[64px]">
                            {children}
                        </main>
                        <Footer />
                    </ScrollProvider>
                </MyThemeProvider>
            </body>
        </html>
    );
}
