-- hero_post: curated posts shown in the home page hero slider.
create table if not exists public.hero_post (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.post(id) on delete cascade,
  display_order int not null default 0,
  created_at timestamptz not null default now(),
  unique (post_id)
);

create index if not exists hero_post_display_order_idx on public.hero_post (display_order asc, id asc);

alter table public.hero_post enable row level security;

drop policy if exists "hero_post is readable by anyone" on public.hero_post;
create policy "hero_post is readable by anyone"
  on public.hero_post
  for select
  to anon, authenticated
  using (true);

-- Hero posts ordered by display_order. Returns the same jsonb shape as
-- get_posts so the front-end mapper can be reused.
create or replace function public.get_hero_posts()
returns table (
  post jsonb,
  post_detail jsonb
)
language sql
stable
as $$
  select
    to_jsonb(p) as post,
    to_jsonb(pd) as post_detail
  from public.hero_post h
  join public.post p on p.id = h.post_id
  left join public.post_detail pd on pd.post_id = p.id
  where p.published = true
  order by h.display_order asc, h.id asc;
$$;

grant execute on function public.get_hero_posts() to anon, authenticated;

-- N random published posts. Server-side random so the front-end no longer
-- needs the full post list to sample from.
create or replace function public.get_random_posts(p_limit int default 5)
returns table (
  post jsonb,
  post_detail jsonb
)
language sql
volatile
as $$
  select
    to_jsonb(p) as post,
    to_jsonb(pd) as post_detail
  from public.post p
  left join public.post_detail pd on pd.post_id = p.id
  where p.published = true
  order by random()
  limit greatest(coalesce(p_limit, 5), 0);
$$;

grant execute on function public.get_random_posts(int) to anon, authenticated;
