-- category catalog mirroring the series table structure.
-- post.category remains a text column; this table is a managed catalog
-- so the editor dropdown has a known list with optional metadata.
create table if not exists public.category (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  thumbnail_url text,
  created_at timestamptz not null default now()
);

alter table public.category enable row level security;

drop policy if exists "category is readable by anyone" on public.category;
create policy "category is readable by anyone"
  on public.category
  for select
  to anon, authenticated
  using (true);

-- backfill distinct categories already used by existing posts
insert into public.category (name)
select distinct p.category
from public.post p
where p.category is not null and length(trim(p.category)) > 0
on conflict (name) do nothing;
